site_name: Waze
theme:
  name: 'material'
  logo: 'img/docs_dir/waze_48px.ico'

extra_css:
  - css/extra_css.css

nav:
  - Home: README.md
  - Planejamento: planejamento.md
  - Pr√©-Rastreabilidade: 
    - RichPicture: richPicture.md
