site_name: Waze
repo_name: 'Repositório de Requisitos Waze'
repo_url: 'https://github.com/Requisitos2-2019/2019.2-Waze'
theme:
  name: 'material'
  logo: 'img/docs_dir/waze_48px.ico'

extra_css:
  - css/extra_css.css

nav:
  - Home: README.md
  - Planejamento: planejamento.md
  - Pré-Rastreabilidade: 
    - RichPicture: richPicture.md
    - 5W2H: 5W2H.md
  - Elicitação de requisitos :
    - Análise de Protocolo: analiseProtocolo.md
    - Brainstorm : Brainstorm.md
    - Entrevista: Entrevista.md
    - Introspecção: introspeccao.md
    - Questionário: Questionario.md
    - Storytelling: Storytelling.md
  - Modelagem:
    - Caso de Uso : CasoDeUso.md
    - Cenários: Cenarios.md
    - Especificação Suplementar: EspSuplementar.md
    - Léxico Ampliado da Linguagem: Lexico.md
  - Ágil:
    - Backlog: ProductBacklog.md
    - História de Usuários: UserStories.md
    - NFR framework: NFR.md
  - Personas: Personas.md
  - Análise: 
    - Verificação Casos de Uso: VerificacaoCasoDeUso.md
    - Verificação Cenário: VerificacaoCenarios.md
    - Verificação Léxico: verificacaolexico.md
    - Verificação NFR: Verificacao-NFR.md
    - Verificação Rich Picture: Verificacao-RichPicture.md
  - Validação: 
    - Entrevista: Entrevista-Prototipo.md
    - Prototipagem: Validacao-Prototipo.md
  - Pós-Rastreabilidade:
    - Backward Form: Backward-form.md
    - Forward Form: forwardForm.md
  

