site_name: Waze
repo_name: 'Repositório de Requisitos Waze'
repo_url: 'https://github.com/Requisitos2-2019/2019.2-Waze'
theme:
  name: 'material'
  logo: 'img/docs_dir/waze_48px.ico'

extra_css:
  - css/extra_css.css

nav:
  - Home: README.md
  - Planejamento: planejamento.md
  - Pré-Rastreabilidade: 
    - RichPicture: richPicture.md
    - 5W2H: 5W2H.md
  - Elicitação de requisitos :
    - Entrevista: Entrevista.md
    - Introspecção: introspeccao.md
    - Questionário: Questionario.md
    - Storytelling: Storytelling.md
    - Análise de Protocolo: analiseProtocolo.md
    - Brainstorm : Brainstorm.md
  - Modelagem:
    - Especificação Suplementar: EspSuplementar.md
    - Cenários: Cenarios.md
    - Léxico Ampliado da Linguagem: Lexico.md
    - Caso de Uso : CasoDeUso.md
  - Ágil:
    - Backlog: ProductBacklog.md
    - História de Usuários: UserStories.md
    - NFR framework: NFR.md
  - Personas: Personas.md
  - Análise: 
    - Verificação Casos de Uso: VerificacaoCasoDeUso.md
    - Verificação Rich Picture: Verificacao-RichPicture.md
    - Verificação Cenário: VerificacaoCenarios.md

  
