site_name: Waze
theme:
  name: 'material'
  logo: 'img/docs_dir/waze_48px.ico'

extra_css:
  - css/extra_css.css

nav:
  - Home: README.md
  - Planejamento: planejamento.md
  - Pré-Rastreabilidade: 
    - RichPicture: richPicture.md
    - 5W2H: 5W2H.md
  - Elicitação de requisitos :
    - Entrevista: Entrevista.md
    - Introspecção: introspeccao.md
    - Questionário: Questionario.md
    - Storytelling: Storytelling.md
    - Análise de Protocolo: analiseProtocolo.md
  - Modelagem:
    - Especificação Suplementar: EspSuplementar.md
    - Cenários: Cenarios.md
    - Léxico Ampliado da Linguagem: Lexico.md
    - Caso de Uso : CasoDeUso.md
  - Pesonas: Personas.md
  
    
